paths:
  base_dir: "/work/cvcs2026/stochastic_parrots"
  instance_images_dir: "/work/cvcs2026/stochastic_parrots/data/instance_images"
  class_images_dir: "/work/cvcs2026/stochastic_parrots/data/class_images"
  random_images_dir: "/work/cvcs2026/stochastic_parrots/data/random_images"
  base_model_dir: "/work/cvcs2026/stochastic_parrots/models/pretrained/sdxl-base"
  lora_model_dir: "/work/cvcs2026/stochastic_parrots/models/trained/lora_cat_v1"
  lora_output_test_dir: "/work/cvcs2026/stochastic_parrots/experiments/lora/test/test_images"
  evaluation_dir: "/work/cvcs2026/stochastic_parrots/evaluation"

weights_file:
  lora_weights: "pytorch_lora_weights.safetensors"


hyperparameters:
  variant: "fp16"
  resolution: 1024
  learning_rate: 1e-4
  max_train_steps: 500
  checkpointing_steps: 250